# Generated by Django 5.0.1 on 2024-02-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('room_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('offer', models.BooleanField()),
                ('price_night', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('cancellation', models.CharField(max_length=255)),
                ('is_booked', models.BooleanField()),
                ('amenities', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.room')),
            ],
        ),
    ]
